### ISSUE TITLE
Not able to run properly

### ISSUE THREAD

**Issue by rakeshbci** [Matthewjsiv/Person-Tracking-Tello-Drone#1]
When I run the python script and take off. I get the following output and drone move crazy and crashes.

Traceback (most recent call last):
  File "track_person.py", line 254, in main
    cv2.imshow('posenet', overlay_image)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-z5gfhs5a\opencv\modules\highgui\src\window.cpp:651: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'

OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-z5gfhs5a\opencv\modules\highgui\src\window.cpp:651: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'

Tello: 09:51:43.900:  Info: counter_clockwise(val=100)
Tello: 09:51:43.901:  Info: up(val=80)
Tello: 09:51:43.901:  Info: forward(val=50)
Traceback (most recent call last):
  File "track_person.py", line 273, in <module>
    main()
  File "track_person.py", line 266, in main
    cv2.destroyAllWindows()
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-z5gfhs5a\opencv\modules\highgui\src\window.cpp:645: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'

Tello: 09:59:09.468:  Info: counter_clockwise(val=100)
Tello: 09:59:09.469:  Info: up(val=80)
Tello: 09:59:09.469:  Info: forward(val=50)

**Comment by rakeshbci** [comment]
I installed the using pip install opencv-python and contrib instead of the headless.

**Comment by Matthewjsiv** [comment]
Just saw this but thanks! I updated the readme to try to make it a little more clear.
